### ISSUE TITLE
Text does not update, though editor is launched

### ISSUE THREAD

**Issue by jwdevel** [rosmanov/chrome-bee#3]
I am having trouble getting this to work on my system — it's as if the modified temp file is never transmitted back to Firefox.

I'm using Firefox 60.8esr

Here's what I have done:

* I cloned https://github.com/rosmanov/chrome-bee
* In that dir, I ran `./host/install.sh ~/.local/opt/chrome-bee`
    * that succeeded; output:
```
Saved cache into /home/myuser/path/to/chrome-bee/host/vars.cache.sh
Installed host application into '/home/myuser/.local/opt/chrome-bee/beectl'
Installed Chrome manifest into '/home/myuser/.config/google-chrome/NativeMessagingHosts/com.ruslan_osmanov.bee.json'
Installed Firefox manifest into '/home/myuser/.mozilla/native-messaging-hosts/com.ruslan_osmanov.bee.json'
```
* I installed the [FF extension](https://addons.mozilla.org/en-US/firefox/addon/external-editor/)
    * Configured the extension to run `gvim`

* I went to a page with a textbox, and hit `Ctrl+E`.

This launched the editor, with the correct text filled in (yay).
However, when I write the file and quit gvim, the text box is not updated.

While the editor is open, I do see `beectl` running:

```
$ ps auxwww | grep 'be[e]'
myuser        687  1.0  0.0  20168 11776 ?        S    13:01   0:00 python2 /home/myuser/.local/opt/chrome-bee/beectl /home/myuser/.mozilla/native-messaging-hosts/com.ruslan_osmanov.bee.json bee@ruslan_osmanov.com
myuser        688  9.0  0.1  87944 34872 ?        S    13:01   0:00 gvim -f /tmp/chrome_bee_mRPpN5.txt
```

So, most of the parts seem to be working.
But the final result is not...

When I do this, there are no errors or messages in the Firefox console.

**Comment by rosmanov** [comment]
Unfortunately, I couldn't reproduce the issue in Firefox 69.0.1 with Python 2.7.15 and, I'm afraid, have no ideas what could be wrong. If you copied the messages from the error console (see below), it would be easier for me to figure out what can be wrong with your setup.

Extension errors are not written to the main error console, since extensions are run in some kind of sandboxed environments. The error console can be reached from `about:debugging#/runtime/this-firefox` through "Inspect" button. Could you look there?

Also, there is an irritating bug that doesn't allow you to save the text when you switch to another tab. I'll try to fix it when I have some free time.

By the way, there is an experimental host native app written in C here: https://github.com/rosmanov/bee-host . Not that I'd recommend using it instead, but it could just work. However, it is not completed and probably should be re-written in modern C++.

**Comment by jwdevel** [comment]
Hi — I couldn't quite figure out your `about:debugging#...` link or Inspect button reference, but I was able to run the "Debug" button on the `about:debugging` page, and from there got some logging; maybe this is the same as what you refer to?

When I close the external editor, this is printed:

`Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.`

This originates from [eventPage.js line 26](https://github.com/rosmanov/chrome-bee/blob/master/js/eventPage.js#L26).

I'll see if I can install a newer Firefox and see if that behaves differently.

**Comment by jwdevel** [comment]
Well, I got Textern working, so I think I'm giving up on this one for now — sorry ):

I'll close the issue.

**Comment by rosmanov** [comment]
I've fixed the bug where the text was not updated after closing editor, if the text area was not in the active tab.

Also, I have written a [host app in C](https://github.com/rosmanov/bee-host) and built packages for the most popular Linux distributions plus Windows binaries. The files are available for download from [SourceForge](https://sourceforge.net/projects/beectl/).

**Comment by rosmanov** [comment]
@jwdevel, well, sorry, I could not reproduce the issue as you described it. But if something goes wrong with Textern, you might want to check out the new host app with the fixed version of the extension.
