### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by 532910** [rosmanov/chrome-bee#4]
I've:
1. Installed host application (python3), exactly:
  a. copied [`beectl-py3.py`](https://github.com/rosmanov/chrome-bee/blob/master/host/beectl-py3.py) into `~/.local/bin`
  b. copied [`firefox-com.ruslan_osmanov.bee.json`](https://github.com/rosmanov/chrome-bee/blob/master/host/firefox-com.ruslan_osmanov.bee.json) and updated the `path` to the `/home/sergio/.local/bin/beectl-py3.py`
2. Installed addon from [AMO](https://addons.mozilla.org/en-US/firefox/addon/external-editor/)

There is no toolbar button or any context menu options appeared after installation. How should I start editing text in external editor?

I tried to configure the extension the same way as shown on the screenshot, without success.

**Comment by rosmanov** [comment]
There are some wiki pages over here: https://github.com/rosmanov/chrome-bee/wiki/Configuration but try to explain it in simple words:

1. [Install a host application](https://github.com/rosmanov/chrome-bee/wiki/Installing-Host-Application)
```
$ mkdir -p ~/src/chrome-bee
$ cd ~/src/chrome-bee
$ wget -q -O - https://github.com/rosmanov/chrome-bee/archive/master.tar.gz | tar xzvf - --strip-components 1
$ ./host/install.sh
Saved cache into /home/ruslan/src/chrome-bee/host/vars.cache.sh
Installed host application into '/home/ruslan/src/chrome-bee/host/beectl'
Installed Chrome manifest into '/home/ruslan/.config/google-chrome/NativeMessagingHosts/com.ruslan_osmanov.bee.json'
Installed Firefox manifest into '/home/ruslan/.mozilla/native-messaging-hosts/com.ruslan_osmanov.bee.json'
```
2. Install the addon in the browser
3. [Configure the addon in the browser](https://github.com/rosmanov/chrome-bee/wiki/Configuration-in-Firefox) (open about:addons). For example,
- Set path to /usr/bin/gvim -f
- Set shortcut to Ctrl + E

-----

Note 1: consider using [bee-host](https://github.com/rosmanov/bee-host) app instead of the Python script
Note 2: I don't remember all steps required for configuring the host app, so I've written a shell script for Python and created packages for popular distributions at https://sourceforge.net/projects/beectl/

**Comment by 532910** [comment]
Aaah, `Ctrl + e`! I believe this must be specified on AMO page and at the top of https://github.com/rosmanov/chrome-bee. As this combination is too unclear!

Also `firefox-com.ruslan_osmanov.bee.json` should be named `com.ruslan_osmanov.bee.json`. This is done in the installation scripts but what's the problem with keeping the same name as desires for those who prefer to install it manually?

**Comment by rosmanov** [comment]
> Aaah, Ctrl + e! I believe this must be specified on AMO page and at the top of https://github.com/rosmanov/chrome-bee. As this combination is too unclear!

Added a note to the add-on page.

> Also firefox-com.ruslan_osmanov.bee.json should be named com.ruslan_osmanov.bee.json. This is done in the installation scripts but what's the problem with keeping the same name as desires for those who prefer to install it manually?

That's right. I didn't think of this when I ported it to Firefox, sorry. Moved it to host/firefox/com.ruslan_osmanov.bee.json.

**Comment by 532910** [comment]
Thank you, Ruslan!

> to uninstall the Python

I've copied it and removed manually (:
